version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # Replace with a strong password
    volumes:
      - mysql-persistent-data:/var/lib/mysql  # Replace with your desired volume name

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql-persistent-data:
    # Replace with your desired volume name or path on the host machine

#####it start withcommand
#docker compose up --build -d
